version: "3"
services:
  minio:
    container_name: minio
    image: quay.io/minio/minio
    ports: 
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=lintang
      - MINIO_ROOT_PASSWORD=lintang123
    user: 1000:1000
    volumes:  
      - ${HOME}/minio/data:/data
    command: server /data --console-address ":9001"
    networks:
      - lintang-video-transcoder

  mongo:
    container_name: mongo
    image: mongo:4.4.14-rc0-focal
    mem_limit: "800mb"
    cpus: 1
    restart: unless-stopped
    ports:
      - "27017:27017"
    expose:
      - "27017"
    networks:
      - lintang-video-transcoder
      
  rabbitmq:
    image: rabbitmq:3.13.1-management
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
       test: rabbitmq-diagnostics -q ping
       interval: 30s
       timeout: 30s
       retries: 3
    networks:
      - lintang-video-transcoder


  dkron:
    image: dkron/dkron:3.2.7
    container_name: dkron
    ports:
      - 9911:8080
    volumes:
      - ./dkron_curl.sh:/curl/curl.sh
      - /etc/localtime:/etc/localtime:ro # biar time di container ini samaa dengan time di laptopku
    command: agent --server --bootstrap-expect=1 --node-name=node1
    networks:
      - lintang-video-transcoder

  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy-minio # biar presigned url minio bisa diakses di host (laptopku) 
    mem_limit: 300mb
    cpus: 0.5
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9091:80
      - 443:443
    depends_on:
      - dkron
    networks:
      - lintang-video-transcoder


networks:
  lintang-video-transcoder:
    external: true




