version: "3"
services:
  minio:
      container_name: minio
      image: quay.io/minio/minio
      ports: 
        - 9000:9000
        - 9001:9001
      environment:
        - MINIO_ROOT_USER=lintang
        - MINIO_ROOT_PASSWORD=lintang123
      user: 1000:1000
      volumes:  
        - ${HOME}/minio/data:/data
      command: server /data --console-address ":9001"
      