---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lintang-transcoder-api
spec:
  selector:
    matchLabels:
      app: lintang-transcoder-api
  template:
    metadata:
      labels:
        app:  lintang-transcoder-api
    spec:
      containers:
      - name:  lintang-transcoder-api
        image: docker.io/lintangbirdas/transcoder-api:v2
        imagePullPolicy: Always
        env:
          - name: MONGO_URL
            value: mongodb://admin:lintang@example-mongodb-0.example-mongodb-svc.mongodb.svc.cluster.local:27017,example-mongodb-1.example-mongodb-svc.mongodb.svc.cluster.local:27017,example-mongodb-2.example-mongodb-svc.mongodb.svc.cluster.local:27017/admin?replicaSet=example-mongodb&ssl=false
          - name: RABBIT_URL
            value: amqp://default_user_qBofhrkSzzUoEDWve1t:ZciKwWU3f4ev5dFjmBnIMNDnvr4MjKfr@10.108.25.30:5672/   # ganti username sama passwordnya dg username password rabbit mq kamu , cara nampilinnya ada di step 2c-2f  #rabbitmq.default.svc.cluster.local gakbisa 
          - name: BASE_URL_MINIO # default_user_Z4KRpZEzc-7wictHAsl 0vpV52fDOzbx2UtHFMRDotjw27pvzB1w%
            value: minio.minio-dev.svc.cluster.local:9000
          - name: DKRON_URL
            value: http://dkron-svc:8080/v1/jobs
          - name: TRANSCODER_WORKER_URL
            value: lintang-transcoder-worker-service.default.svc.cluster.local:9995
          - name: ACC_KEY_MINIO
            value: oO3LIXBYLXmIXxG5t6FD  # ganti dg access key yang kamu buat di minio, caranya ada di step 3f-3g
          - name: SECRET_KEY_MINIO
            value: kuxo6ec5rgyIwMh8jVdNFk5nCyWutOnHC1gyutKp  # ganti dg secret key yang kamu buat di minio, caranya ada di step 3f-3g
          - name: APP_ENV
            value: k8s
          - name: Minikube_IP
            value: 192.168.49.2 # isi dg minikube ipmu, `minikube ip`
        resources:
          limits:
            memory: "500Mi"
            cpu: "400m"
        ports:
        - containerPort: 9996
  

---
apiVersion: v1
kind: Service
metadata:
  name: lintang-transcoder-api-service
spec:
  selector: 
    app: lintang-transcoder-api
  ports:
    - port: 9996
      targetPort: 9996
      nodePort: 31203
  type: NodePort

    