apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-minio
spec:
  ports:
    - port: 9091
      targetPort: 80
      nodePort: 30009
  type: NodePort
  selector:
    app: reverse-proxy-minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy-minio
  template:
    metadata:
      labels:
        app: reverse-proxy-minio
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
          - mountPath: /etc/nginx
            name: reverse-proxy-minio-config
      volumes:
        - name: reverse-proxy-minio-config
          configMap: 
            name: reverse-proxy-minio-config